# Generated by Django 5.0.1 on 2024-02-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_event_employee_attending_events_memo_pto_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_img_url',
            field=models.TextField(default='#'),
        ),
    ]
