# Generated by Django 5.0.1 on 2024-02-07 11:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_event_employee_attending_events_memo_pto_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='pto_request',
            name='employee_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
