# Generated by Django 5.0.1 on 2024-02-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_event_event_img_url'),
        ('main_app', '0005_pto_request_employee_name'),
    ]

    operations = [
    ]
