# Generated by Django 5.0.1 on 2024-02-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_employee_attending_events_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(default='default@email.com', max_length=255),
            preserve_default=False,
        ),
    ]
