# Generated by Django 5.0.1 on 2024-02-08 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_employee_attending_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pto_request',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.employee'),
        ),
    ]
