# Generated by Django 5.0.1 on 2024-02-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_pto_request_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
